services:
- type: pserv
  repo: https://github.com/AbelRR/agent-deployments

  # Change this to the path containing your Dockerfile
  rootDir: .

  name: agent-example
  runtime: image

  # Ensure this image is available on Docker Hub
  image: docker.io/abelregalado/render-image:latest

  # Free plan is not available for private services
  plan: starter

  # Ensure this environment variable group exists in Render
  envVars:
  - fromGroup: agent
  region: oregon

  # 300s is the standard allowed maximum. Talk to render.com support if you need this increased.
  maxShutdownDelaySeconds: 300

  # Sane defaults for scaling
  scaling:
    minInstances: 1
    maxInstances: 4
    targetCPUPercent: 60
    targetMemoryPercent: 60

version: "1"